function createfigure(xvector1, ymatrix1)
%CREATEFIGURE(xvector1, ymatrix1)
%  XVECTOR1:  bar xvector
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 27-Mar-2020 10:19:44

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to bar
bar(xvector1,ymatrix1,'BaseValue',20000000);

% Create text
text('Parent',axes1,'String','standard placement production25272977.6578W',...
    'Position',[0.278645833333333 0.54375982532751 0]);

% Create text
text('Parent',axes1,'String','standard placement production25272977.6578W',...
    'Position',[0.278645833333333 0.54375982532751 0]);

% Create text
text('Parent',axes1,'String','standard placement production25272977.6578W',...
    'Position',[0.278645833333333 0.54375982532751 0]);

% Create ylabel
ylabel({'W'});

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[20000000 30000000]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XTick',zeros(1,0));
% Create textbox
annotation(figure1,'textbox',...
    [0.278645833333333 0.54375982532751 0.126302083333333 0.0480349344978166],...
    'String','standard placement production:25272977.6578 W',...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',...
    [0.453645833333332 0.695506550218337 0.126302083333333 0.0480349344978167],...
    'String','75-percentile placement production:26991296.5789 W',...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',...
    [0.616145833333333 0.786026200873362 0.1546875 0.0655938864628778],...
    'String',{'75-percentile with threshold placement','production:28150759.0755 W'},...
    'FitBoxToText','off');

